
# SnapLogic Pipeline Generator Web Tool
# Requires: streamlit, openai

import json
import openai
import os
import streamlit as st
from typing import Dict, Any

openai.api_key = os.getenv("OPENAI_API_KEY") or "sk-your-key"

SNAP_TEMPLATES = {
    "Salesforce Read": lambda object_name: {
        "label": "Read Contacts",
        "type": "Salesforce Read",
        "settings": {"object": object_name}
    },
    "Filter": lambda expression: {
        "label": "Filter",
        "type": "Filter",
        "settings": {"expression": expression}
    },
    "Mapper": lambda mappings: {
        "label": "Map Fields",
        "type": "Mapper",
        "settings": {"mappings": mappings}
    },
    "REST POST": lambda url: {
        "label": "Post to API",
        "type": "REST POST",
        "settings": {"url": url}
    }
}

def generate_pipeline(requirement: Dict[str, Any]) -> Dict:
    pipeline = {
        "name": "AutoGeneratedPipeline",
        "snaps": []
    }

    if requirement.get("source", {}).get("type") == "Salesforce":
        pipeline["snaps"].append(SNAP_TEMPLATES["Salesforce Read"](requirement["source"].get("object")))

    if "filter" in requirement:
        pipeline["snaps"].append(SNAP_TEMPLATES["Filter"](requirement["filter"]))

    if "mapping" in requirement:
        pipeline["snaps"].append(SNAP_TEMPLATES["Mapper"](requirement["mapping"]))

    if requirement.get("target", {}).get("type") == "REST POST":
        pipeline["snaps"].append(SNAP_TEMPLATES["REST POST"](requirement["target"].get("url")))

    return pipeline

def parse_natural_language(nl_input: str) -> Dict[str, Any]:
    prompt = f"""
    Convert the following natural language SnapLogic pipeline requirement into structured JSON with keys: source, filter, mapping, target.

    Example Input:
    Read customer data from Salesforce where status is 'Active'. Map FirstName to fname and LastName to lname. Post to REST API https://api.example.com/users.

    Example Output:
    {{
      "source": {{"type": "Salesforce", "object": "Contact"}},
      "filter": "$Status == 'Active'",
      "mapping": {{"FirstName": "fname", "LastName": "lname"}},
      "target": {{"type": "REST POST", "url": "https://api.example.com/users"}}
    }}

    Now convert this:
    """
    prompt += nl_input

    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2
    )

    json_str = response.choices[0].message['content']
    return json.loads(json_str)

# Streamlit UI
st.set_page_config(page_title="SnapLogic Auto-Generator", layout="wide")
st.title("🔧 SnapLogic Pipeline Generator")

mode = st.radio("Choose Input Mode", ["Natural Language", "Structured JSON"])

input_text = st.text_area("Paste your requirement here:", height=200)

if st.button("Generate Pipeline JSON"):
    try:
        if mode == "Natural Language":
            structured = parse_natural_language(input_text)
        else:
            structured = json.loads(input_text)

        result = generate_pipeline(structured)

        st.subheader("🧾 SnapLogic JSON")
        st.code(json.dumps(result, indent=2), language="json")
        st.download_button("📥 Download JSON", data=json.dumps(result, indent=2), file_name="snaplogic_pipeline.json", mime="application/json")

    except Exception as e:
        st.error(f"❌ Error: {e}")
